version: "3"

volumes:
  data:

networks:
  strapi-app-network:
    driver: bridge

services:
  strapi-app:
    container_name: strapi-app
    build: .
    image: strapi-app:0.0.1
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: postgresDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    links:
      - postgresDB:postgresDB
    volumes:
      - ./src:/srv/app/src
    ports:
      - "3000:3000"
    networks:
      - strapi-app-network
    depends_on:
      - postgresDB

  postgresDB:
    image: postgres:15.1
    container_name: postgresDB
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi-app-network
